import Footer from "@/components/shared/Footer";
import Nav from "@/components/shared/Nav";
import ExerciseProvider from "@/Contexts/ExerciseContext";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fit LOG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"
        />
      </head>
      <body className="min-h-full flex flex-col bg-black">
        <ExerciseProvider>
          <Nav></Nav>
          <div>{children}</div>
          <Footer></Footer>
          <ToastContainer />
        </ExerciseProvider>
      </body>
    </html>
  );
}
